#! /bin/sh

. "${PM_FUNCTIONS}"

test_pulse_system() {
    getent passwd pulse | awk -F: '{print $3}'
}

get_pulse_users() {
    PULSE_SYSTEM_USER=$(test_pulse_system)
    if [ -z "$PULSE_SYSTEM_USER" ]; then
        ps -C pulseaudio -o uid= | tr -d ' '
    else
        ps -C pulseaudio -o uid= | tr -d ' ' | sed s/$PULSE_SYSTEM_USER//
    fi
}

# $1 = sink|source
# $2 = uid
save_pulse_state_and_mute() {
    sudo -H -u \#$2 pacmd list-${1}s | \
        sed -n 's/^[[:space:]*]*//; /\(index\|mute\)/p' | \
        (index="";
            while read field value; do
                if [ ${field%:} = "index" ]; then
                    index=$value
                else
                    savestate pulse:$2:$1$index $value
                    sudo -H -u \#$2 pacmd set-$1-mute $index yes
                fi
            done)
}

# $1 = sink|source
# $2 = uid
restore_pulse_state() {
    sudo -H -u \#$2 pacmd list-${1}s | \
        sed -n 's/^[[:space:]*]*index: //p' | \
        while read index; do
            if state_exists pulse:$2:$1$index; then
                sudo -H -u \#$2 pacmd \
                    set-$1-mute \
                    $index \
                    $(restorestate pulse:$2:$1$index);
            fi
        done
}

suspend_pulse() {
    for i in $(get_pulse_users); do
        save_pulse_state_and_mute sink $i
        save_pulse_state_and_mute source $i
        sudo -H -u \#$i pacmd suspend true
    done
}

resume_pulse() {
    for i in $(get_pulse_users); do
        restore_pulse_state sink $i
        restore_pulse_state source $i
        sudo -H -u \#$i pacmd suspend false
    done
}

case $1 in
    hibernate|suspend)
        suspend_pulse
        ;;
    thaw|resume)
        resume_pulse
        ;;
    *) exit $NA
        ;;
esac
